// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMessesAdmin = `-- name: CountActiveMessesAdmin :one
SELECT count(DISTINCT tenant_id)::int FROM memberships WHERE left_at IS NULL
`

// A mess with anyone still in it. Zero-write days keep it "active".
func (q *Queries) CountActiveMessesAdmin(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveMessesAdmin)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countClosesBetweenAdmin = `-- name: CountClosesBetweenAdmin :one
SELECT count(*)::int FROM periods
WHERE status = 'CLOSED' AND closed_at >= $1 AND closed_at < $2
`

type CountClosesBetweenAdminParams struct {
	Since pgtype.Timestamptz `json:"since"`
	Until pgtype.Timestamptz `json:"until"`
}

func (q *Queries) CountClosesBetweenAdmin(ctx context.Context, arg CountClosesBetweenAdminParams) (int32, error) {
	row := q.db.QueryRow(ctx, countClosesBetweenAdmin, arg.Since, arg.Until)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countExceptionsBetweenAdmin = `-- name: CountExceptionsBetweenAdmin :one
SELECT count(*)::int FROM meal_exceptions
WHERE created_at >= $1 AND created_at < $2
`

type CountExceptionsBetweenAdminParams struct {
	Since pgtype.Timestamptz `json:"since"`
	Until pgtype.Timestamptz `json:"until"`
}

func (q *Queries) CountExceptionsBetweenAdmin(ctx context.Context, arg CountExceptionsBetweenAdminParams) (int32, error) {
	row := q.db.QueryRow(ctx, countExceptionsBetweenAdmin, arg.Since, arg.Until)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMemberLinksOpenedAdmin = `-- name: CountMemberLinksOpenedAdmin :one
SELECT count(*)::int FROM memberships WHERE invite_opened_at IS NOT NULL
`

func (q *Queries) CountMemberLinksOpenedAdmin(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMemberLinksOpenedAdmin)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenantsAdmin = `-- name: CountTenantsAdmin :one
SELECT count(*)::int FROM tenants t
WHERE $1::text = '' OR t.name ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountTenantsAdmin(ctx context.Context, query string) (int32, error) {
	row := q.db.QueryRow(ctx, countTenantsAdmin, query)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findUserByFirebaseAdmin = `-- name: FindUserByFirebaseAdmin :one
SELECT id, firebase_uid, phone_e164, name, locale, use_bangla_numerals, created_at, deleted_at FROM users WHERE firebase_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByFirebaseAdmin(ctx context.Context, firebaseUid *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByFirebaseAdmin, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.PhoneE164,
		&i.Name,
		&i.Locale,
		&i.UseBanglaNumerals,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByPhoneAdmin = `-- name: FindUserByPhoneAdmin :one
SELECT id, firebase_uid, phone_e164, name, locale, use_bangla_numerals, created_at, deleted_at FROM users WHERE phone_e164 = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByPhoneAdmin(ctx context.Context, phoneE164 *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhoneAdmin, phoneE164)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.PhoneE164,
		&i.Name,
		&i.Locale,
		&i.UseBanglaNumerals,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit_log (id, staff_uid, action, target, request_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAdminAuditParams struct {
	ID        uuid.UUID `json:"id"`
	StaffUid  string    `json:"staff_uid"`
	Action    string    `json:"action"`
	Target    *string   `json:"target"`
	RequestID *string   `json:"request_id"`
}

// Task 16.8: who read what, and when.
func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.ID,
		arg.StaffUid,
		arg.Action,
		arg.Target,
		arg.RequestID,
	)
	return err
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, value FROM feature_flags ORDER BY key
`

type ListFeatureFlagsRow struct {
	Key   string `json:"key"`
	Value bool   `json:"value"`
}

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]ListFeatureFlagsRow, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureFlagsRow
	for rows.Next() {
		var i ListFeatureFlagsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsAdmin = `-- name: ListTenantsAdmin :many

SELECT
    t.id,
    t.name,
    t.kind,
    (SELECT count(*) FROM memberships m
       WHERE m.tenant_id = t.id AND m.left_at IS NULL)::int AS member_count,
    t.created_at,
    GREATEST(
        t.created_at,
        COALESCE((SELECT max(created_at) FROM meal_exceptions me WHERE me.tenant_id = t.id), t.created_at),
        COALESCE((SELECT max(created_at) FROM ledger_entries le WHERE le.tenant_id = t.id), t.created_at)
    )::timestamptz AS last_activity_at
FROM tenants t
WHERE $1::text = '' OR t.name ILIKE '%' || $1::text || '%'
ORDER BY last_activity_at DESC
LIMIT $3 OFFSET $2
`

type ListTenantsAdminParams struct {
	Query string `json:"query"`
	Off   int32  `json:"off"`
	Lim   int32  `json:"lim"`
}

type ListTenantsAdminRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Kind           string             `json:"kind"`
	MemberCount    int32              `json:"member_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
}

// Epic 16 — the admin portal's reads. Every one runs as tinbela_admin
// (ADR-0016): BYPASSRLS for cross-tenant reach, SELECT-only on customer data.
// The two writes here touch admin's own tables, never a mess's.
// Tenant search + list (task 16.3), most-recently-active first. member_count
// and last_activity are derived on read, never stored (Invariant 3).
func (q *Queries) ListTenantsAdmin(ctx context.Context, arg ListTenantsAdminParams) ([]ListTenantsAdminRow, error) {
	rows, err := q.db.Query(ctx, listTenantsAdmin, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsAdminRow
	for rows.Next() {
		var i ListTenantsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.MemberCount,
			&i.CreatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeatureFlag = `-- name: SetFeatureFlag :exec
INSERT INTO feature_flags (key, value, updated_at, updated_by)
VALUES ($1, $2, now(), $3)
ON CONFLICT (key) DO UPDATE
    SET value = EXCLUDED.value, updated_at = now(), updated_by = EXCLUDED.updated_by
`

type SetFeatureFlagParams struct {
	Key       string  `json:"key"`
	Value     bool    `json:"value"`
	UpdatedBy *string `json:"updated_by"`
}

// The one write the admin surface makes to a shared switch (task 16.6). Takes
// effect on the next read of the flag, no deploy.
func (q *Queries) SetFeatureFlag(ctx context.Context, arg SetFeatureFlagParams) error {
	_, err := q.db.Exec(ctx, setFeatureFlag, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
