// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_writes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    id, tenant_id, user_id, role, display_name, joined_at, invite_token
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, group_id, role, fee_category, display_name, joined_at, left_at, invite_token, invite_opened_at, created_at
`

type CreateMembershipParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
	DisplayName string      `json:"display_name"`
	JoinedAt    pgtype.Date `json:"joined_at"`
	InviteToken *string     `json:"invite_token"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.DisplayName,
		arg.JoinedAt,
		arg.InviteToken,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.FeeCategory,
		&i.DisplayName,
		&i.JoinedAt,
		&i.LeftAt,
		&i.InviteToken,
		&i.InviteOpenedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO periods (id, tenant_id, start_date, end_date, status)
VALUES ($1, $2, $3, $4, 'OPEN')
RETURNING id, tenant_id, start_date, end_date, status, closed_at, created_at
`

type CreatePeriodParams struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.ID,
		arg.TenantID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSlot = `-- name: CreateSlot :one
INSERT INTO slots (id, tenant_id, name_bn, name_en, sort_order, cutoff_local, active)
VALUES ($1, $2, $3, $4, $5, $6::time, true)
RETURNING id, tenant_id, name_bn, name_en, sort_order, cutoff_local, active
`

type CreateSlotParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	NameBn      string      `json:"name_bn"`
	NameEn      string      `json:"name_en"`
	SortOrder   int32       `json:"sort_order"`
	CutoffLocal pgtype.Time `json:"cutoff_local"`
}

func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.ID,
		arg.TenantID,
		arg.NameBn,
		arg.NameEn,
		arg.SortOrder,
		arg.CutoffLocal,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NameBn,
		&i.NameEn,
		&i.SortOrder,
		&i.CutoffLocal,
		&i.Active,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, kind, billing_mode, timezone)
VALUES ($1, $2, $3, 'RATE_BASED', 'Asia/Dhaka')
RETURNING id, name, kind, billing_mode, timezone, created_at
`

type CreateTenantParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Kind string    `json:"kind"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name, arg.Kind)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BillingMode,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getSlotsForTenant = `-- name: GetSlotsForTenant :many
SELECT id, tenant_id, name_bn, name_en, sort_order, cutoff_local, active FROM slots
WHERE tenant_id = $1
ORDER BY sort_order
`

func (q *Queries) GetSlotsForTenant(ctx context.Context, tenantID uuid.UUID) ([]Slot, error) {
	rows, err := q.db.Query(ctx, getSlotsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NameBn,
			&i.NameEn,
			&i.SortOrder,
			&i.CutoffLocal,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersWithUser = `-- name: ListMembersWithUser :many
SELECT m.id, m.tenant_id, m.user_id, m.group_id, m.role, m.fee_category, m.display_name, m.joined_at, m.left_at, m.invite_token, m.invite_opened_at, m.created_at, u.phone_e164 AS user_phone
FROM memberships m
LEFT JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1 AND m.left_at IS NULL
ORDER BY m.display_name
`

type ListMembersWithUserRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	Role           string             `json:"role"`
	FeeCategory    *string            `json:"fee_category"`
	DisplayName    string             `json:"display_name"`
	JoinedAt       pgtype.Date        `json:"joined_at"`
	LeftAt         pgtype.Date        `json:"left_at"`
	InviteToken    *string            `json:"invite_token"`
	InviteOpenedAt pgtype.Timestamptz `json:"invite_opened_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UserPhone      *string            `json:"user_phone"`
}

// Members of a mess, with the linked user where one exists. A member may
// have no account at all -- the manager adds them by name, and the invite
// link is what turns them into a user later.
func (q *Queries) ListMembersWithUser(ctx context.Context, tenantID uuid.UUID) ([]ListMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listMembersWithUser, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersWithUserRow
	for rows.Next() {
		var i ListMembersWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.FeeCategory,
			&i.DisplayName,
			&i.JoinedAt,
			&i.LeftAt,
			&i.InviteToken,
			&i.InviteOpenedAt,
			&i.CreatedAt,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
