// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOpenPeriod = `-- name: GetOpenPeriod :one
SELECT id, tenant_id, start_date, end_date, status, closed_at, created_at FROM periods
WHERE tenant_id = $1 AND status = 'OPEN'
ORDER BY start_date DESC
LIMIT 1
`

func (q *Queries) GetOpenPeriod(ctx context.Context, tenantID uuid.UUID) (Period, error) {
	row := q.db.QueryRow(ctx, getOpenPeriod, tenantID)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (
    id, tenant_id, kind, amount_paisa, category, membership_id,
    occurred_on, note, photo_url, entered_by, void_of
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, kind, amount_paisa, category, membership_id, occurred_on, note, photo_url, entered_by, void_of, created_at
`

type InsertLedgerEntryParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	Kind         string      `json:"kind"`
	AmountPaisa  int64       `json:"amount_paisa"`
	Category     *string     `json:"category"`
	MembershipID pgtype.UUID `json:"membership_id"`
	OccurredOn   pgtype.Date `json:"occurred_on"`
	Note         *string     `json:"note"`
	PhotoUrl     *string     `json:"photo_url"`
	EnteredBy    uuid.UUID   `json:"entered_by"`
	VoidOf       pgtype.UUID `json:"void_of"`
}

// Append only. Corrections insert a negative row with void_of set.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.AmountPaisa,
		arg.Category,
		arg.MembershipID,
		arg.OccurredOn,
		arg.Note,
		arg.PhotoUrl,
		arg.EnteredBy,
		arg.VoidOf,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.AmountPaisa,
		&i.Category,
		&i.MembershipID,
		&i.OccurredOn,
		&i.Note,
		&i.PhotoUrl,
		&i.EnteredBy,
		&i.VoidOf,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesForRange = `-- name: ListLedgerEntriesForRange :many
SELECT id, tenant_id, kind, amount_paisa, category, membership_id, occurred_on, note, photo_url, entered_by, void_of, created_at FROM ledger_entries
WHERE tenant_id = $1
  AND occurred_on BETWEEN $2::date AND $3::date
ORDER BY occurred_on, created_at
`

type ListLedgerEntriesForRangeParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	RangeStart pgtype.Date `json:"range_start"`
	RangeEnd   pgtype.Date `json:"range_end"`
}

// Hits ledger_tenant_date_idx (tenant_id, occurred_on).
func (q *Queries) ListLedgerEntriesForRange(ctx context.Context, arg ListLedgerEntriesForRangeParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesForRange, arg.TenantID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.AmountPaisa,
			&i.Category,
			&i.MembershipID,
			&i.OccurredOn,
			&i.Note,
			&i.PhotoUrl,
			&i.EnteredBy,
			&i.VoidOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDepositsForMembership = `-- name: SumDepositsForMembership :one
SELECT COALESCE(sum(amount_paisa), 0)::bigint FROM ledger_entries
WHERE tenant_id = $1
  AND membership_id = $2
  AND kind = 'DEPOSIT'
`

type SumDepositsForMembershipParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

func (q *Queries) SumDepositsForMembership(ctx context.Context, arg SumDepositsForMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumDepositsForMembership, arg.TenantID, arg.MembershipID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumFoodCostForRange = `-- name: SumFoodCostForRange :one
SELECT COALESCE(sum(amount_paisa), 0)::bigint FROM ledger_entries
WHERE tenant_id = $1
  AND kind = 'FOOD_COST'
  AND occurred_on BETWEEN $2::date AND $3::date
`

type SumFoodCostForRangeParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	RangeStart pgtype.Date `json:"range_start"`
	RangeEnd   pgtype.Date `json:"range_end"`
}

// Voided entries are cancelled by their negative counterpart, so a plain
// SUM over both is already correct -- no filtering on void_of.
func (q *Queries) SumFoodCostForRange(ctx context.Context, arg SumFoodCostForRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumFoodCostForRange, arg.TenantID, arg.RangeStart, arg.RangeEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
