// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMealException = `-- name: InsertMealException :one
INSERT INTO meal_exceptions (
    id, tenant_id, membership_id, slot_id, date_from, date_to,
    action, qty, marked_by, after_cutoff, void_of
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, membership_id, slot_id, date_from, date_to, action, qty, marked_by, after_cutoff, void_of, created_at
`

type InsertMealExceptionParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	MembershipID uuid.UUID   `json:"membership_id"`
	SlotID       pgtype.UUID `json:"slot_id"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	Action       string      `json:"action"`
	Qty          *int16      `json:"qty"`
	MarkedBy     uuid.UUID   `json:"marked_by"`
	AfterCutoff  bool        `json:"after_cutoff"`
	VoidOf       pgtype.UUID `json:"void_of"`
}

// Append only. A correction sets void_of; nothing is ever updated.
func (q *Queries) InsertMealException(ctx context.Context, arg InsertMealExceptionParams) (MealException, error) {
	row := q.db.QueryRow(ctx, insertMealException,
		arg.ID,
		arg.TenantID,
		arg.MembershipID,
		arg.SlotID,
		arg.DateFrom,
		arg.DateTo,
		arg.Action,
		arg.Qty,
		arg.MarkedBy,
		arg.AfterCutoff,
		arg.VoidOf,
	)
	var i MealException
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MembershipID,
		&i.SlotID,
		&i.DateFrom,
		&i.DateTo,
		&i.Action,
		&i.Qty,
		&i.MarkedBy,
		&i.AfterCutoff,
		&i.VoidOf,
		&i.CreatedAt,
	)
	return i, err
}

const listDayFlags = `-- name: ListDayFlags :many
SELECT id, tenant_id, date, kind, note FROM day_flags
WHERE tenant_id = $1
  AND date BETWEEN $2::date AND $3::date
ORDER BY date
`

type ListDayFlagsParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	RangeStart pgtype.Date `json:"range_start"`
	RangeEnd   pgtype.Date `json:"range_end"`
}

func (q *Queries) ListDayFlags(ctx context.Context, arg ListDayFlagsParams) ([]DayFlag, error) {
	rows, err := q.db.Query(ctx, listDayFlags, arg.TenantID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayFlag
	for rows.Next() {
		var i DayFlag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.Kind,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptionsForDate = `-- name: ListExceptionsForDate :many
SELECT id, tenant_id, membership_id, slot_id, date_from, date_to, action, qty, marked_by, after_cutoff, void_of, created_at FROM meal_exceptions
WHERE tenant_id = $1
  AND date_from <= $2::date
  AND date_to   >= $2::date
ORDER BY created_at
`

type ListExceptionsForDateParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	OnDate   pgtype.Date `json:"on_date"`
}

// The day query. Hits meal_exceptions_lookup_idx (tenant_id, date_from,
// date_to) -- see docs/eng/indexes.md. A row is in force on a date when the
// date falls inside its closed range.
func (q *Queries) ListExceptionsForDate(ctx context.Context, arg ListExceptionsForDateParams) ([]MealException, error) {
	rows, err := q.db.Query(ctx, listExceptionsForDate, arg.TenantID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealException
	for rows.Next() {
		var i MealException
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MembershipID,
			&i.SlotID,
			&i.DateFrom,
			&i.DateTo,
			&i.Action,
			&i.Qty,
			&i.MarkedBy,
			&i.AfterCutoff,
			&i.VoidOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptionsForRange = `-- name: ListExceptionsForRange :many
SELECT id, tenant_id, membership_id, slot_id, date_from, date_to, action, qty, marked_by, after_cutoff, void_of, created_at FROM meal_exceptions
WHERE tenant_id = $1
  AND date_from <= $2::date
  AND date_to   >= $3::date
ORDER BY created_at
`

type ListExceptionsForRangeParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	RangeEnd   pgtype.Date `json:"range_end"`
	RangeStart pgtype.Date `json:"range_start"`
}

func (q *Queries) ListExceptionsForRange(ctx context.Context, arg ListExceptionsForRangeParams) ([]MealException, error) {
	rows, err := q.db.Query(ctx, listExceptionsForRange, arg.TenantID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealException
	for rows.Next() {
		var i MealException
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MembershipID,
			&i.SlotID,
			&i.DateFrom,
			&i.DateTo,
			&i.Action,
			&i.Qty,
			&i.MarkedBy,
			&i.AfterCutoff,
			&i.VoidOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatterns = `-- name: ListPatterns :many
SELECT id, tenant_id, membership_id, slot_id, dow_mask, qty, effective_from, created_at FROM patterns
WHERE tenant_id = $1 AND effective_from <= $2::date
ORDER BY membership_id, slot_id, effective_from DESC
`

type ListPatternsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	AsOf     pgtype.Date `json:"as_of"`
}

// Law 1 defaults. effective_from lets a pattern change mid-period without
// rewriting history.
func (q *Queries) ListPatterns(ctx context.Context, arg ListPatternsParams) ([]Pattern, error) {
	rows, err := q.db.Query(ctx, listPatterns, arg.TenantID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pattern
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MembershipID,
			&i.SlotID,
			&i.DowMask,
			&i.Qty,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPattern = `-- name: UpsertPattern :one
INSERT INTO patterns (
    id, tenant_id, membership_id, slot_id, dow_mask, qty, effective_from
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (membership_id, slot_id, effective_from)
DO UPDATE SET dow_mask = EXCLUDED.dow_mask, qty = EXCLUDED.qty
RETURNING id, tenant_id, membership_id, slot_id, dow_mask, qty, effective_from, created_at
`

type UpsertPatternParams struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	MembershipID  uuid.UUID   `json:"membership_id"`
	SlotID        uuid.UUID   `json:"slot_id"`
	DowMask       int16       `json:"dow_mask"`
	Qty           int16       `json:"qty"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
}

// Law 1: a member's weekly default (dow_mask bit 0 = Saturday, 127 = every
// day; qty = plates on an active day). patterns is NOT append-only — a change
// updates the row for its effective date. effective_from lets a change apply
// forward without rewriting past days: ListPatterns picks the latest
// effective_from <= the query date, so history is preserved by a new date, not
// a mutated one.
func (q *Queries) UpsertPattern(ctx context.Context, arg UpsertPatternParams) (Pattern, error) {
	row := q.db.QueryRow(ctx, upsertPattern,
		arg.ID,
		arg.TenantID,
		arg.MembershipID,
		arg.SlotID,
		arg.DowMask,
		arg.Qty,
		arg.EffectiveFrom,
	)
	var i Pattern
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MembershipID,
		&i.SlotID,
		&i.DowMask,
		&i.Qty,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}
