// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveMembers = `-- name: CountActiveMembers :one
SELECT count(*) FROM memberships
WHERE tenant_id = $1 AND left_at IS NULL AND role <> 'MANAGER'
`

func (q *Queries) CountActiveMembers(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMembers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, tenant_id, user_id, group_id, role, fee_category, display_name, joined_at, left_at, invite_token, invite_opened_at, created_at FROM memberships
WHERE tenant_id = $1 AND id = $2
`

type GetMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TenantID, arg.ID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.FeeCategory,
		&i.DisplayName,
		&i.JoinedAt,
		&i.LeftAt,
		&i.InviteToken,
		&i.InviteOpenedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT id, tenant_id, user_id, group_id, role, fee_category, display_name, joined_at, left_at, invite_token, invite_opened_at, created_at FROM memberships
WHERE tenant_id = $1 AND left_at IS NULL
ORDER BY display_name
`

// Everyone currently in the mess. left_at IS NULL is the "still here" test.
func (q *Queries) ListMemberships(ctx context.Context, tenantID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMemberships, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.FeeCategory,
			&i.DisplayName,
			&i.JoinedAt,
			&i.LeftAt,
			&i.InviteToken,
			&i.InviteOpenedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
