// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DayFlag struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Kind     string      `json:"kind"`
	Note     *string     `json:"note"`
}

type Group struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	Kind     *string     `json:"kind"`
}

type LedgerEntry struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Kind         string             `json:"kind"`
	AmountPaisa  int64              `json:"amount_paisa"`
	Category     *string            `json:"category"`
	MembershipID pgtype.UUID        `json:"membership_id"`
	OccurredOn   pgtype.Date        `json:"occurred_on"`
	Note         *string            `json:"note"`
	PhotoUrl     *string            `json:"photo_url"`
	EnteredBy    uuid.UUID          `json:"entered_by"`
	VoidOf       pgtype.UUID        `json:"void_of"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MealException struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	MembershipID uuid.UUID          `json:"membership_id"`
	SlotID       pgtype.UUID        `json:"slot_id"`
	DateFrom     pgtype.Date        `json:"date_from"`
	DateTo       pgtype.Date        `json:"date_to"`
	Action       string             `json:"action"`
	Qty          *int16             `json:"qty"`
	MarkedBy     uuid.UUID          `json:"marked_by"`
	AfterCutoff  bool               `json:"after_cutoff"`
	VoidOf       pgtype.UUID        `json:"void_of"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	Role           string             `json:"role"`
	FeeCategory    *string            `json:"fee_category"`
	DisplayName    string             `json:"display_name"`
	JoinedAt       pgtype.Date        `json:"joined_at"`
	LeftAt         pgtype.Date        `json:"left_at"`
	InviteToken    *string            `json:"invite_token"`
	InviteOpenedAt pgtype.Timestamptz `json:"invite_opened_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Pattern struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	MembershipID  uuid.UUID          `json:"membership_id"`
	SlotID        uuid.UUID          `json:"slot_id"`
	DowMask       int16              `json:"dow_mask"`
	Qty           int16              `json:"qty"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Period struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Status    string             `json:"status"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PeriodStatement struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	PeriodID        uuid.UUID          `json:"period_id"`
	MembershipID    uuid.UUID          `json:"membership_id"`
	MealsQty        int32              `json:"meals_qty"`
	MealRatePaisa   int64              `json:"meal_rate_paisa"`
	FoodCostPaisa   int64              `json:"food_cost_paisa"`
	SharedCostPaisa int64              `json:"shared_cost_paisa"`
	DepositsPaisa   int64              `json:"deposits_paisa"`
	BalancePaisa    int64              `json:"balance_paisa"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
}

type Slot struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	NameBn      string      `json:"name_bn"`
	NameEn      string      `json:"name_en"`
	SortOrder   int32       `json:"sort_order"`
	CutoffLocal pgtype.Time `json:"cutoff_local"`
	Active      bool        `json:"active"`
}

type Tenant struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	BillingMode string             `json:"billing_mode"`
	Timezone    string             `json:"timezone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	FirebaseUid       *string            `json:"firebase_uid"`
	PhoneE164         *string            `json:"phone_e164"`
	Name              string             `json:"name"`
	Locale            string             `json:"locale"`
	UseBanglaNumerals bool               `json:"use_bangla_numerals"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}
