// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT id, name, kind, billing_mode, timezone, created_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BillingMode,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSlots = `-- name: ListActiveSlots :many
SELECT id, tenant_id, name_bn, name_en, sort_order, cutoff_local, active FROM slots
WHERE tenant_id = $1 AND active
ORDER BY sort_order
`

func (q *Queries) ListActiveSlots(ctx context.Context, tenantID uuid.UUID) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listActiveSlots, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NameBn,
			&i.NameEn,
			&i.SortOrder,
			&i.CutoffLocal,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
