// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMembershipForUserInTenant = `-- name: GetMembershipForUserInTenant :one
SELECT id, tenant_id, user_id, group_id, role, fee_category, display_name, joined_at, left_at, invite_token, invite_opened_at, created_at FROM memberships
WHERE user_id = $1 AND tenant_id = $2 AND left_at IS NULL
`

type GetMembershipForUserInTenantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

// The tenant interceptor's authorisation check: is this caller in this mess?
func (q *Queries) GetMembershipForUserInTenant(ctx context.Context, arg GetMembershipForUserInTenantParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUserInTenant, arg.UserID, arg.TenantID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.FeeCategory,
		&i.DisplayName,
		&i.JoinedAt,
		&i.LeftAt,
		&i.InviteToken,
		&i.InviteOpenedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, firebase_uid, phone_e164, name, locale, use_bangla_numerals, created_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.PhoneE164,
		&i.Name,
		&i.Locale,
		&i.UseBanglaNumerals,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, phone_e164, name, locale, use_bangla_numerals, created_at, deleted_at FROM users
WHERE firebase_uid = $1 AND deleted_at IS NULL
`

// Auth runs before any tenant is known, which is why `users` carries no RLS
// policy: a user may belong to several messes, and identity is resolved
// before scope is.
func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.PhoneE164,
		&i.Name,
		&i.Locale,
		&i.UseBanglaNumerals,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessesForUser = `-- name: ListMessesForUser :many
SELECT t.id, t.name, t.kind, t.billing_mode, t.timezone, t.created_at, m.id AS membership_id, m.role, m.display_name
FROM tenants t
JOIN memberships m ON m.tenant_id = t.id
WHERE m.user_id = $1 AND m.left_at IS NULL
ORDER BY t.name
`

type ListMessesForUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Kind         string             `json:"kind"`
	BillingMode  string             `json:"billing_mode"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MembershipID uuid.UUID          `json:"membership_id"`
	Role         string             `json:"role"`
	DisplayName  string             `json:"display_name"`
}

// Every mess this user still belongs to, with their membership in it.
func (q *Queries) ListMessesForUser(ctx context.Context, userID pgtype.UUID) ([]ListMessesForUserRow, error) {
	rows, err := q.db.Query(ctx, listMessesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessesForUserRow
	for rows.Next() {
		var i ListMessesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BillingMode,
			&i.Timezone,
			&i.CreatedAt,
			&i.MembershipID,
			&i.Role,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
