ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM tinbela_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE USAGE, SELECT ON SEQUENCES FROM tinbela_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM tinbela_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM tinbela_app;
REVOKE USAGE ON SCHEMA public FROM tinbela_app;
DROP ROLE IF EXISTS tinbela_app;
