import type { Metadata, Viewport } from 'next';
import { Hind_Siliguri } from 'next/font/google';

import { color } from '@/lib/tokens';

import './globals.css';

// next/font self-hosts the file at build time, so there is no request to
// fonts.googleapis.com at runtime. On a throttled 3G connection that round
// trip alone is a meaningful slice of the 3s budget (UX law 3).
const hindSiliguri = Hind_Siliguri({
  subsets: ['bengali', 'latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
  variable: '--font-hind-siliguri',
});

// Task 15.7 — SEO basics + the Messenger link preview. The invite link is
// shared into a mess group chat, so og:title/description/image ARE the first
// impression of the whole product. The OG image is generated by
// app/opengraph-image.tsx; Next injects og:image / twitter:image from it for
// every route under this segment, so every page previews correctly.
//
// metadataBase is the production origin (the same host invite links use); it is
// what turns the relative OG image path into the absolute URL Messenger fetches.
export const metadata: Metadata = {
  metadataBase: new URL('https://tinbela.app'),
  title: {
    default: 'টিনবেলা — স্বাভাবিক দিনে কিছুই করতে হবে না।',
    template: '%s · টিনবেলা',
  },
  description: 'মেসের খাবার আর হিসাব — একটাই অ্যাপে। স্বাভাবিক দিনে কিছুই করতে হবে না।',
  applicationName: 'টিনবেলা',
  manifest: '/manifest.webmanifest',
  alternates: { canonical: '/' },
  robots: { index: true, follow: true },
  openGraph: {
    type: 'website',
    siteName: 'টিনবেলা',
    // bn-BD is the audience; the app and this site are Bangla-first.
    locale: 'bn_BD',
    url: '/',
    title: 'টিনবেলা — স্বাভাবিক দিনে কিছুই করতে হবে না।',
    description: 'মেসের খাবার আর হিসাব — একটাই অ্যাপে।',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'টিনবেলা',
    description: 'মেসের খাবার আর হিসাব — স্বাভাবিক দিনে কিছুই করতে হবে না।',
  },
};

export const viewport: Viewport = {
  themeColor: color.primary,
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // lang="bn" is load-bearing, not decoration: it selects Bangla line
  // breaking and tells a screen reader which language it is reading.
  return (
    <html lang="bn" className={hindSiliguri.variable}>
      <body className={hindSiliguri.className}>{children}</body>
    </html>
  );
}
