#!/usr/bin/env node
// Generates the Dart theme, Tailwind config, and CSS variables from
// tokens.json (ADR-0014). One token change propagates to all three clients.
//
// Run: make tokens

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const t = JSON.parse(readFileSync(new URL("./tokens.json", import.meta.url)));
const write = (p, s) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, s); console.log("  ✓", p); };
const hexToDart = (h) => `0xFF${h.slice(1).toUpperCase()}`;
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// ── Dart theme ──────────────────────────────────────────────────
let dart = `// GENERATED by packages/design-tokens/generate.mjs — DO NOT EDIT.
// Run \`make tokens\` after changing tokens.json.
import 'package:flutter/material.dart';

abstract final class TinBelaColors {
`;
for (const [k, v] of Object.entries(t.color)) {
  dart += `  /// ${v.use}\n  static const ${camel(k)} = Color(${hexToDart(v.value)});\n`;
}
dart += `}

abstract final class TinBelaSpace {
`;
for (const [k, v] of Object.entries(t.space)) dart += `  static const double ${k} = ${v};\n`;
dart += `}

abstract final class TinBelaRadius {
`;
for (const [k, v] of Object.entries(t.radius)) dart += `  static const double ${k} = ${v};\n`;
dart += `}

abstract final class TinBelaTouch {
  /// Non-negotiable minimum touch target.
  static const double min = ${t.touch.min};
}
`;
write("apps/manager/lib/core/theme/tokens.g.dart", dart);

// ── Tailwind ────────────────────────────────────────────────────
const colors = Object.fromEntries(Object.entries(t.color).map(([k, v]) => [k, v.value]));
write("packages/design-tokens/tailwind.tokens.js",
`// GENERATED — DO NOT EDIT. Run \`make tokens\`.
module.exports = {
  colors: ${JSON.stringify(colors, null, 2)},
  borderRadius: ${JSON.stringify(Object.fromEntries(Object.entries(t.radius).map(([k, v]) => [k, v + "px"])), null, 2)},
  spacing: ${JSON.stringify(Object.fromEntries(Object.entries(t.space).map(([k, v]) => [k, v + "px"])), null, 2)},
};
`);

// ── CSS variables ───────────────────────────────────────────────
let css = "/* GENERATED — DO NOT EDIT. Run `make tokens`. */\n:root {\n";
for (const [k, v] of Object.entries(t.color)) css += `  --tb-${k}: ${v.value};\n`;
for (const [k, v] of Object.entries(t.space)) css += `  --tb-space-${k}: ${v}px;\n`;
for (const [k, v] of Object.entries(t.radius)) css += `  --tb-radius-${k}: ${v}px;\n`;
css += `  --tb-touch-min: ${t.touch.min}px;\n}\n`;
write("packages/design-tokens/tokens.css", css);

console.log("✓ design tokens generated for Dart, Tailwind, and CSS");
